<?php

/**
 * @file course_fill.module
 */

/**
 * Implements hook_menu().
 *
 * Sets up calls to autocomplete callbacks
 *
 */
function course_fill_menu() {
	$items = array();
	$items['course_fill/user_autocomplete_callback'] = array(
		'page callback' => 'course_fill_user_autocomplete_callback',
		'access callback' => TRUE,
	);
	return $items;
}

/**
 *
 * @param $string
 *   The string that will be searched.
 */
function course_fill_user_autocomplete_callback($string = '') {
	$matches = array();
	if ($string && strlen($string) > 6) {
		$staff_names = &drupal_static(__FUNCTION__);
		
		if (!isset($staff_info)) {
			$json = file_get_contents(drupal_get_path('module', 'course_fill') . '/' . 'courses.json');
			$staff_info_php = json_decode($json);
			$staff_names = array_keys(get_object_vars($staff_info_php));
		}
		$names = preg_grep("/$string/i", $staff_names);
		$matches = array_combine($names, $names);
	}

	drupal_json_output($matches);
}

function course_fill_form_alter(&$form, &$form_state, $form_id) {
	if (preg_match('/^(ufal_course_node_form)$/', $form_id)) {
		// attach the ajax autocomplete
		$form['title']['#autocomplete_path'] = 'course_fill/user_autocomplete_callback';
		
		// attach the ajax values prefiller
		$form['title']['#ajax'] = array(
			'callback' => 'course_form_callback',
			'wrapper'  => 'course_replace_div',
		);
		$form['#prefix'] = '<div id="course_replace_div">';
		$form['#suffix'] = '</div>';
		
		if (!empty($form_state['values']['field_sis_code'])) {
			$username   = $form_state['values']['field_sis_code'];
			$staff_info = course_get_staff_info($username);
			
			$textfields = array(
				'title'       => 'title_field',
				'annotation'  => 'field_annotation',
				'literature'  => 'field_literature',
				'syllabus'    => 'field_syllabus',
			);
			foreach ($textfields as $index => $destination) {
				// DO NOT Check if we got info && destination is empty so far
				//if (isset($staff_info->$index) && empty($form_state['values'][$destination]['und'][0]['value'])) {
				if (isset($staff_info->$index->en)) {
					$value = $staff_info->$index->en;
				} else if (isset($staff_info->$index)) {
					$value = $staff_info->$index;
				}
			}
		}
	}
}

function course_select_pre_render($element) {
	// tmp stored, picking up here
	$element['und']['select']['#value'] = array($element['und']['#default_value'][0]);
	return $element;
}
function course_other_pre_render($element) {
	// tmp stored, picking up here
	$element['und']['select']['#value'] = 'select_or_other';
	$element['und']['other']['#value'] = array($element['und']['#default_value'][0]);
	return $element;
}

function course_form_callback($form, &$form_state) {
	return $form;
}

function course_get_staff_info($user_name) {
	$staff_info = &drupal_static(__FUNCTION__);
	
	if (!isset($staff_info)) {
		$json = file_get_contents(drupal_get_path('module', 'course_fill') . '/' . 'courses.json');
		$staff_info = json_decode($json);
	}
	
	return @$staff_info->$user_name;
}