<?php

/**
 * @file course_fill.module
 */

/**
 * Implements hook_menu().
 *
 * Sets up calls to autocomplete callbacks
 *
 */
function course_fill_menu() {
	$items = array();
	$items['course_fill/user_autocomplete_callback'] = array(
		'page callback' => 'course_fill_user_autocomplete_callback',
		'access callback' => TRUE,
	);
	return $items;
}

/**
 *
 * @param $string
 *   The string that will be searched.
 */
function course_fill_user_autocomplete_callback($string = '') {
	$matches = array();
	if ($string && strlen($string) > 4) {
		$staff_names = &drupal_static(__FUNCTION__);
		
		if (!isset($staff_info)) {
			$json = file_get_contents(drupal_get_path('module', 'course_fill') . '/' . 'courses.json');
			$staff_info_php = json_decode($json);
			$staff_names = array_keys(get_object_vars($staff_info_php));
		}
		$names = preg_grep("/$string/i", $staff_names);
		$matches = array_combine($names, $names);
	}

	drupal_json_output($matches);
}

function course_fill_form_alter(&$form, &$form_state, $form_id) {
	if (preg_match('/^(ufal_course_node_form)$/', $form_id)) {
		// attach the ajax autocomplete
		$form['field_sis_code']['und'][0]['value']['#autocomplete_path'] = 'course_fill/user_autocomplete_callback';
		
		// attach the ajax values prefiller
		$form['field_sis_code']['und'][0]['value']['#ajax'] = array(
			'callback' => 'course_form_callback',
			'wrapper'  => 'course_replace_div',
		);
		$form['#prefix'] = '<div id="course_replace_div">';
		$form['#suffix'] = '</div>';
		
		if (!empty($form_state['values']['field_sis_code'])) {
			$username   = $form_state['values']['field_sis_code']['und'][0]['value'];
			$staff_info = course_get_staff_info($username);
			
			$textfields = array(
				'title'       => 'title_field',
				'annotation'  => 'field_annotation',
				'literature'  => 'field_literature',
				'syllabus'    => 'field_syllabus',
				'Semester:'   => 'field_semester',
				'E-Credits:'  => 'field_e_credits',
				'examination' => 'field_examination',
				'Guarantor:'  => 'field_guarantor',
			);
			foreach ($textfields as $index => $destination) {
				// DO NOT Check if we got info && destination is empty so far
				//if (isset($staff_info->$index) && empty($form_state['values'][$destination]['und'][0]['value'])) {
				if (!is_scalar($staff_info->$index)) {
					$value = '';
					if (isset($staff_info->$index->en)) {
						$value = $staff_info->$index->en;
					}
					if (isset($staff_info->$index->cs)) {
						$value = $staff_info->$index->cs;
					}
				} else {
					$value = $staff_info->$index;
				}
				$form[$destination]['und'][0]['value']['#value'] = $value;
				if (preg_match('/^(annotation|literature|syllabus)/', $index)) {
					$form[$destination]['#pre_render'] = array('course_textarea_pre_render');
					// tmp store it in default value, pick it up in the prerender
					$form[$destination]['und']['#default_value'] = $value;
					$form['#after_build'] = array('course_fill_after_build');
				}
			}
		}
	}
}

function course_fill_after_build($form, &$form_state) {
	$fields = array('field_annotation', 'field_literature', 'field_syllabus');
	foreach ($fields as $field) {
		$form[$field]['und'][0]['value']['#attributes']['readonly'] = 'readonly';
		//$form_state['values'][$field]['und'][0]['value'] = $form[$field]['und'][0]['value']['#default_value'];
	}
	return $form;
}

function course_select_pre_render($element) {
	// tmp stored, picking up here
	$element['und']['select']['#value'] = array($element['und']['#default_value'][0]);
	return $element;
}
function course_textarea_pre_render($element) {
	// tmp stored, picking up here
	$element['und'][0]['value']['#value'] = $element['und']['#default_value'];
	return $element;
}
function course_other_pre_render($element) {
	// tmp stored, picking up here
	$element['und']['select']['#value'] = 'select_or_other';
	$element['und']['other']['#value'] = array($element['und']['#default_value'][0]);
	return $element;
}

function course_form_callback($form, &$form_state) {
	return $form;
}

function course_get_staff_info($user_name) {
	$staff_info = &drupal_static(__FUNCTION__);
	
	if (!isset($staff_info)) {
		$json = file_get_contents(drupal_get_path('module', 'course_fill') . '/' . 'courses.json');
		$staff_info = json_decode($json);
	}
	
	return @$staff_info->$user_name;
}
